// <auto-generated />
using ComplaintsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplaintsApi.Migrations
{
    [DbContext(typeof(ComplaintDbContext))]
    partial class ComplaintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ComplaintsApi.Models.Complaint", b =>
                {
                    b.Property<long>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ComplaintId"), 1L, 1);

                    b.Property<int>("Addres")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplaintText")
                        .HasColumnType("int");

                    b.Property<int>("EMail")
                        .HasColumnType("int");

                    b.Property<int>("EcpCode")
                        .HasColumnType("int");

                    b.Property<long>("FilesFileId")
                        .HasColumnType("bigint");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<int>("IndicationId")
                        .HasColumnType("int");

                    b.Property<int>("LotNomer")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PinFl")
                        .HasColumnType("bigint");

                    b.Property<int>("SigningDate")
                        .HasColumnType("int");

                    b.Property<int>("SipId")
                        .HasColumnType("int");

                    b.Property<int>("Tin")
                        .HasColumnType("int");

                    b.Property<int>("UniqueNumber")
                        .HasColumnType("int");

                    b.HasKey("ComplaintId");

                    b.HasIndex("FilesFileId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("ComplaintsApi.Models.File", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileId"), 1L, 1);

                    b.Property<string>("FileContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("ComplaintsApi.Models.Complaint", b =>
                {
                    b.HasOne("ComplaintsApi.Models.File", "Files")
                        .WithMany()
                        .HasForeignKey("FilesFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
